language: node_js
git:
  depth: 1
node_js:
  - "10"

cache:
  directories:
    - node_modules # NPM packages

install:
    - npm install --force

script:
    - npm test
    - npm run eslint
    - npm run stylelint
